-- ============================================================
-- backlog_items 초기 데이터 (53건)
-- create_backlog_items.sql 실행 후 이 파일을 실행하세요
-- ============================================================

INSERT INTO public.backlog_items (category, name, jira_ticket, status, department, assignees, sort_order) VALUES
  ('Search',   'Search 가격 계산 > 품절/판매중지 상품 제외',                                                          'PROJ-9113',  '예정', 'BE',  '{"강성훈"}',  0),
  ('Order',    'toss payments로 결제시 partner_id 누락되는 이슈',                                                      NULL,         '보류', 'BE',  '{"강성훈"}',  1),
  ('Item',     'EP > search_tag 개선',                                                                                  'PROJ-9000',  '예정', 'PM',  '{"조용익"}',  2),
  ('Web',      '도메인 별 auth 관련 로직 통일 (only cookie 기반으로 SSoT)',                                             NULL,         '예정', 'FE',  '{"윤영주"}',  3),
  ('Web',      'google search console SEO 도입',                                                                         NULL,         '완료', 'FE',  '{"윤영주"}',  4),
  ('All',      '마수동 동기화 이슈',                                                                                     NULL,         '예정', NULL,  '{}',          5),
  ('All',      '도메인간, 부서간 네이밍 컨벤션 이슈 DD',                                                                NULL,         '예정', NULL,  '{}',          6),
  ('DevOps',   '[Biz-Api] JDK 버전 업그레이드 (JDK 11 -> JDK17)',                                                      'TECH-25306', '완료', 'BE',  '{"심지영"}',  7),
  ('FE',       '3rd party log system 일원화',                                                                            NULL,         '예정', 'FE',  '{"윤영주"}',  8),
  ('DevOps',   'Jenkins -> Github Action 전환',                                                                          NULL,         '예정', 'BE',  '{"심지영"}',  9),
  ('Admin',    '어드민 > 마켓관리 > 상품관리 조회 성능 개선',                                                           NULL,         '예정', 'BE',  '{"강성훈"}',  10),
  ('Web',      'PHP의 session 및 utm handle 관련 node 서버로 분리 이전',                                                NULL,         '예정', NULL,  '{}',          11),
  ('Web',      '기획전 배너 모듈에 영상 관련 확장자 추가 (video ai 생성 기반 영상을 보여주자는 취지)',                   NULL,         '예정', NULL,  '{}',          12),
  ('DevOps',   'HTTP 1.1 -> HTTP 2',                                                                                     NULL,         '대기', NULL,  '{}',          13),
  ('DevOps',   'AWS ElastiCache for Redis OSS 업그레이드 (~2026/1/31)',                                                  NULL,         '완료', 'BE',  '{"심지영"}',  14),
  ('DevOps',   'AWS IAM 권한 정리',                                                                                      NULL,         '예정', 'BE',  '{"심지영"}',  15),
  ('DevOps',   'AWS EKS1.33 버전 업그레이드(~2026/3/23) - Blue-Green 방식 사전 준비 포함',                              NULL,         '완료', 'BE',  '{"심지영"}',  16),
  ('BE',       'AWS MSK 장애 감지 및 Teams 알림 구성',                                                                   NULL,         '예정', 'BE',  '{"김재범"}',  17),
  ('BE',       'main, dev 브랜치 코드 동기화 작업',                                                                      NULL,         '예정', 'BE',  '{"김재범"}',  18),
  ('BE',       '어드민 > 회원관리 > 판매회원 접속 느린 이슈 확인',                                                      NULL,         '예정', 'BE',  '{"강성훈"}',  19),
  ('BE',       '네이버 EP > 제품코드(manufacture_define_number) 전송',                                                   'PROJ-9057',  '예정', 'BE',  '{"강성훈"}',  20),
  ('BE',       'n8n 머스트잇 서비스 장애 분석 자동화(코드, 쿼리, 데이터분석) (AI 에이전트, 워크플로우)',                NULL,         '예정', 'BE',  '{"이동훈"}',  21),
  ('BE',       'QA 자동화 MCP 개발(PRD를 통한 QA리스트 분석, 웹브라우져 크롤링 QA)',                                    NULL,         '예정', 'BE',  '{"이동훈"}',  22),
  ('BE',       '판매자 신용등급에 따른 무료 상품등록개수 제한 로직 제거 필요',                                           NULL,         '예정', 'BE',  '{"김재범"}',  23),
  ('BE',       '팀즈 웹훅 로직 제거 필요 - Teams Workflows로 이관 필요',                                                NULL,         '예정', 'BE',  '{"김재범"}',  24),
  ('BE',       '[카탈로그] 카탈로그 최저가 Search vs Catalog sync 이슈',                                                NULL,         '예정', 'BE',  '{"김재범"}',  25),
  ('BE',       '[결제/PG] 사이트 주문 발생했으나 PG 주문 미접수',                                                       'TECH-25484', '보류', 'BE',  '{"강성훈"}',  26),
  ('BE',       'GitFlow 검토 및 적용',                                                                                   NULL,         '예정', 'BE',  '{}',          27),
  ('DevOps',   '비밀번호 변경 후 로그인되지 않는 이슈 (FAQ 작성)',                                                      NULL,         '예정', 'BE',  '{}',          28),
  ('DevOps',   'MS365, Jira, Wiki, AD 등 계정관련 팀즈채널 신설',                                                       NULL,         '예정', 'BE',  '{}',          29),
  ('BE',       '크론 현황 정리',                                                                                         NULL,         '예정', 'BE',  '{}',          30),
  ('BE',       'partner-stream-cdc-cj-item consume deadlock 이슈 건',                                                    'TECH-25503', '예정', 'BE',  '{"김재범"}',  31),
  ('BE',       '[임직원 복지] 임직원 할인 쿠폰, 생일 적립금 자동 지급 Job - 임직원 할인 쿠폰 자동 생성 로직 수정',     'TECH-25504', '예정', 'BE',  '{}',          32),
  ('FE',       '사용자화면 & 판매자 > 무료/선결제/착불 배송비 금액과 추가배송비 금액 구분 표기',                        NULL,         '예정', NULL,  '{}',          33),
  ('FE',       '판매자 사이트 > 상품등록/수정 페이지 내 추가배송비 관리 팝업 적용하기 버튼 삭제',                       NULL,         '예정', NULL,  '{}',          34),
  ('FE',       '판매자 사이트 > 배송정보관리 페이지 추가배송비 설정 불가 제어 필요(묶음배송 설정 상품)',                 NULL,         '예정', NULL,  '{}',          35),
  ('FE',       '무료배송 + 추가배송비 설정 상품 옵션별 배송비 합산 불가 처리 필요',                                     NULL,         '예정', NULL,  '{}',          36),
  ('BE',       '[SRP/Diver] ''티셔츠'' 등 범용적인 키워드 검색 시, 응답이 느린 이슈 확인',                              NULL,         '예정', NULL,  '{}',          37),
  ('BE',       'search job index 성능개선',                                                                              NULL,         '예정', 'BE',  '{}',          38),
  ('APP',      '[APP] 홈 메인 이동 시, 모든 적층창 창 닫고 이동',                                                       'PROJ-9228',  '완료', 'FE',  '{"윤영주"}',  39),
  ('주문',     '배송지 변경 UX 개선',                                                                                   'PROJ-9229',  '예정', 'FE',  '{}',          40),
  ('BE',       'n8n 운영데이터 분석 AGENT 추가',                                                                         NULL,         '예정', 'BE',  '{"이동훈"}',  41),
  ('Search',   '정렬필터 이슈 개선 (머스트잇 랭킹순 외 상품단위 검색 이슈)',                                            NULL,         '예정', 'PM',  '{"조용익"}',  42),
  ('FE',       'RN + OTA로 현 네이티브 대체가 가능할지 실험',                                                           'TECH-25781', '예정', 'FE',  '{}',          43),
  ('기타',     '인기 상품 자동 추출 및 대시보드화',                                                                     NULL,         '대기', NULL,  '{}',          44),
  ('기타',     '몰로코 홈 인벤토리',                                                                                     NULL,         '대기', NULL,  '{}',          45),
  ('기타',     'AI 이미지 생성 자동화',                                                                                  NULL,         '대기', NULL,  '{}',          46),
  ('기타',     '해외 마켓 판매 구조 전환 (세금계산서 역발행 및 수출 신고)',                                             NULL,         '대기', NULL,  '{}',          47),
  ('기타',     '상품명 AI 클렌징',                                                                                       NULL,         '대기', NULL,  '{}',          48),
  ('FE',       'PDP style review migration',                                                                              'TECH-25791', '완료', 'FE',  '{"조현빈"}',  49),
  ('FE',       'PDP catalog migration',                                                                                   'TECH-25876', '예정', 'FE',  '{"조현빈"}',  50),
  ('FE',       'PDP seller review migration',                                                                             NULL,         '예정', 'FE',  '{"조현빈"}',  51),
  ('FE',       'Naver 로그인 개선',                                                                                       NULL,         '예정', 'FE',  '{}',          52);
